//Histories
export const UPDATE_SESSION_LENGTH = "UPDATE_SESSION_LENGTH";
export const UPDATE_BREAK_LENGTH = "UPDATE_BREAK_LENGTH";
export const LISTEN_UPDATE_SESSION_LENGTH = "LISTEN_UPDATE_SESSION_LENGTH";
export const LISTEN_UPDATE_BREAK_LENGTH = "LISTEN_UPDATE_BREAK_LENGTH";

export const LISTEN_CHANGE_CLOCK_TIME = "LISTEN_CHANGE_CLOCK_TIME";
export const CHANGE_CLOCK_TIME = "CHANGE_CLOCK_TIME";
// Timer
export const TOGGLE_ALARM_SOUND = "TOGGLE_ALARM_SOUND";
export const TOGGLE_AUTO_START = "TOGGLE_AUTO_START";
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const RESET_TIMER = "RESET_TIMER";
export const RUN_TIMER = "RUN_TIMER";
export const AUTO_START_TIMER = "AUTO_START_TIMER";
export const START_BREAK = "START_BREAK";

//History
export const GET_ALL_HISTORIES_FROM_STORE = "GET_ALL_HISTORIES_FROM_STORE";
export const GET_ALL_HISTORIES = "GET_ALL_HISTORIES";
export const SAVE_HISTORY = "SAVE_HISTORY";
export const LISTEN_SAVE_HISTORY = "LISTEN_SAVE_HISTORY";
